dcache:
  build: .
  hostname: zitpcx18435
  domainname: desy.de
  ports:
   - "2049:2049"
   - "2880:2880"
   - "22125:22125"
   - "22224:22224"
  volumes_from:
   - data
  links:
   - db:dcachedb
db:
  image: dcache/db:2.13
  volumes_from:
   - data
data:
  image: ubuntu:latest
  volumes:
   - /pools
   - /var/log/dcache
   - /var/lib/postgresql/data
